[versions]
ravel = "0.2.0"

changelog = "2.4.0"
intellij-platform = "2.10.4"
junit = "4.13.2"
kotlin = "2.1.20"
mapping-io = "0.7.1"
opentest4j = "1.3.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
kotlin-compiler = { group = "org.jetbrains.kotlin", name = "kotlin-compiler", version.ref = "kotlin" }
mapping-io = { group = "net.fabricmc", name = "mapping-io", version.ref = "mapping-io" }
opentest4j = { group = "org.opentest4j", name = "opentest4j", version.ref = "opentest4j" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intellij-platform = { id = "org.jetbrains.intellij.platform", version.ref = "intellij-platform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
